# ===========================
# SKILLSPHERE - Configuración
# ===========================

# Nombre de la aplicación
spring.application.name=skillsphere

# ===========================
# Conexión a PostgreSQL
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/skillsphere_db
spring.datasource.username=postgres
spring.datasource.password=Doky0517*

# ===========================
# JPA / Hibernate
# ===========================
# update = crea las tablas si no existen, las actualiza si cambian
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (útil para aprender)
spring.jpa.show-sql=true

# Formato bonito para las consultas SQL
spring.jpa.properties.hibernate.format_sql=true
